/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */



public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        FLEPIBIRD = new javax.swing.JLabel();
        MulaiBtn = new javax.swing.JButton();
        PetunjukBtn = new javax.swing.JButton();
        KeluarBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(null);

        FLEPIBIRD.setBackground(new java.awt.Color(255, 255, 255));
        FLEPIBIRD.setFont(new java.awt.Font("Karmatic Arcade", 0, 72)); // NOI18N
        FLEPIBIRD.setForeground(new java.awt.Color(255, 255, 255));
        FLEPIBIRD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FLEPIBIRD.setText("FLEPIBIRD");
        FLEPIBIRD.setName(""); // NOI18N
        jPanel1.add(FLEPIBIRD);
        FLEPIBIRD.setBounds(0, 150, 1280, 79);

        MulaiBtn.setBackground(new java.awt.Color(0, 102, 51));
        MulaiBtn.setFont(new java.awt.Font("Press Start 2P", 0, 12)); // NOI18N
        MulaiBtn.setForeground(new java.awt.Color(255, 255, 255));
        MulaiBtn.setText("MULAI");
        MulaiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MulaiBtnActionPerformed(evt);
            }
        });
        jPanel1.add(MulaiBtn);
        MulaiBtn.setBounds(552, 324, 172, 63);

        PetunjukBtn.setBackground(new java.awt.Color(0, 153, 255));
        PetunjukBtn.setFont(new java.awt.Font("Press Start 2P", 0, 12)); // NOI18N
        PetunjukBtn.setForeground(new java.awt.Color(255, 255, 255));
        PetunjukBtn.setText("PETUNJUK");
        PetunjukBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PetunjukBtnActionPerformed(evt);
            }
        });
        jPanel1.add(PetunjukBtn);
        PetunjukBtn.setBounds(552, 405, 172, 63);

        KeluarBtn.setBackground(new java.awt.Color(204, 0, 0));
        KeluarBtn.setFont(new java.awt.Font("Press Start 2P", 0, 12)); // NOI18N
        KeluarBtn.setForeground(new java.awt.Color(255, 255, 255));
        KeluarBtn.setText("KELUAR");
        KeluarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarBtnActionPerformed(evt);
            }
        });
        jPanel1.add(KeluarBtn);
        KeluarBtn.setBounds(552, 486, 172, 63);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgroundFlepi2.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 720);

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PetunjukBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PetunjukBtnActionPerformed
        
    }//GEN-LAST:event_PetunjukBtnActionPerformed

    private void KeluarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_KeluarBtnActionPerformed

    private void MulaiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MulaiBtnActionPerformed
        this.setVisible(false);

        // Menjalankan game temanmu
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FlepiBird(); // panggil game
            }
        });
    }//GEN-LAST:event_MulaiBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FLEPIBIRD;
    private javax.swing.JButton KeluarBtn;
    private javax.swing.JButton MulaiBtn;
    private javax.swing.JButton PetunjukBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
